-- MySQL Script generated by MySQL Workbench
-- Wed Apr 19 08:06:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lab1_individual
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab1_individual
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab1_individual` DEFAULT CHARACTER SET utf8 ;
USE `lab1_individual` ;

-- -----------------------------------------------------
-- Table `lab1_individual`.`supply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_individual`.`supply` (
  `supply_code` INT NOT NULL AUTO_INCREMENT,
  `supply_name` VARCHAR(45) NOT NULL,
  `supply_address` VARCHAR(45) NOT NULL,
  `supply_phone` VARCHAR(10) NOT NULL,
  `supply_boss_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supply_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1_individual`.`assembly_name`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_individual`.`assembly_name` (
  `assembly_name_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`assembly_name_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1_individual`.`assembly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_individual`.`assembly` (
  `assembly_code` INT NOT NULL AUTO_INCREMENT,
  `assembly_name_assembly_name_id` INT NOT NULL,
  `assembly_mfr` VARCHAR(45) NOT NULL,
  `assembly_price` DECIMAL(8,2) NOT NULL,
  `assembly_min_batch` INT NOT NULL,
  `supply_supply_code` INT NOT NULL,
  PRIMARY KEY (`assembly_code`, `assembly_name_assembly_name_id`, `supply_supply_code`),
  INDEX `fk_assembly_supply_idx` (`supply_supply_code` ASC) INVISIBLE,
  UNIQUE INDEX `assembly_code_UNIQUE` (`assembly_code` ASC) VISIBLE,
  INDEX `fk_assembly_assembly_name1_idx` (`assembly_name_assembly_name_id` ASC) VISIBLE,
  CONSTRAINT `fk_assembly_supply`
    FOREIGN KEY (`supply_supply_code`)
    REFERENCES `lab1_individual`.`supply` (`supply_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_assembly_assembly_name1`
    FOREIGN KEY (`assembly_name_assembly_name_id`)
    REFERENCES `lab1_individual`.`assembly_name` (`assembly_name_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1_individual`.`ordering`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_individual`.`ordering` (
  `ordering_code` INT NOT NULL AUTO_INCREMENT,
  `ordering_date` DATE NOT NULL,
  `ordering_term` DATE NOT NULL,
  PRIMARY KEY (`ordering_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab1_individual`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab1_individual`.`order` (
  `ordering_ordering_code` INT NOT NULL,
  `assembly_assembly_code` INT NOT NULL,
  `assembly_assembly_name_assembly_name_id` INT NOT NULL,
  `order_amount` INT NOT NULL,
  PRIMARY KEY (`ordering_ordering_code`),
  INDEX `fk_order_orderingB1_idx` (`ordering_ordering_code` ASC) VISIBLE,
  INDEX `fk_order_assembly1_idx` (`assembly_assembly_code` ASC, `assembly_assembly_name_assembly_name_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_orderingB1`
    FOREIGN KEY (`ordering_ordering_code`)
    REFERENCES `lab1_individual`.`ordering` (`ordering_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_assembly1`
    FOREIGN KEY (`assembly_assembly_code` , `assembly_assembly_name_assembly_name_id`)
    REFERENCES `lab1_individual`.`assembly` (`assembly_code` , `assembly_name_assembly_name_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
